### ISSUE TITLE
[Add Module] Change Flag Texture

### ISSUE THREAD

**Issue by tommibus** [hypoxia125/Modules-Enhanced#26]
Change flag texture.

Area module which would change flag texture on synced flagpole depending which side controls the designated module area. Module would fire when a side has achieved assigned percentage of troops in area over the opposing(previously controlling side).

Needed attributes are the path to flag textures for Bluefor, Opfor and Independent sides and the persentage of troops to control the area.

**Comment by hypoxia125** [comment]
This sounds more like you want a "Controllable Area" module as I would need to script the underlying system rather than just changing the flag texture. Is this a better description of what you want?

It would then need to have some sort of output or getter of the current controlled side so that people could script something on top of it. Probably a scriptedEventHandler people can hook into.

**Comment by tommibus** [comment]
Hi! I am quite new to the game and mission making, but I had this thougt out as just an easy way to create ambient cue to players when capturing areas. And the actual victory conditions would be handled with triggers. But i have close to zero knowledge to what is possiböe and sensible.

**Comment by hypoxia125** [comment]
So here's the thing, if you are using triggers to make the system for your possession, then changing the flag texture is a single line of code, and probably best placed within your triggers.
